spring.application.name=cloud-config-app
spring.profiles.active=development
spring.config.import=configserver:http://localhost:8888
server.port=8080
management.endpoints.web.exposure.include=health,info,env,refresh
management.endpoint.env.post.enabled=true